Larvitar async
dvisionlab/Larvitar pull request #173
Opened 2021-11-04 15:26 UTC by daron1337

Added promises instead of callbacks.

See Migration.md for breaking changes w/ old versions

2021-11-05 10:31 UTC, akiross requested changes
It could be a good chance to also fix a couple of minor inconsistencies:
  - loaders are named `multiframeLoader.js` and `nrrdLoader.js` using camel case, instead all the other files are using `snake_case.js`. It would be nice to rename those files as well.
  - `tools/tools.segmentation.js` have a redundant `tool` in the name, can it be removed?

2021-11-05 10:31 UTC, akiross commented on imaging/image_parsing.js
> + * @returns {Promise} - Return a promise which will resolve to a image object list or fail if an error occurs
This is not returning a Promise, remove this line.

2021-11-05 10:31 UTC, akiross commented on MIGRATION.md
> +This guide is primarily for user with prior Larvitar v0.x experience who want to learn about the new features and changes in Larvitar v1.x. While it looks like a lot has changed, a lot of what you kn
typo: BUT we wanted to be as...

2021-11-05 10:31 UTC, akiross commented on package.json
> +  "version": "1.0.0",
Be sure to include `BREAKING CHANGE: blah` (or use `!` e.g. `fix!: blah`, `feat!: blah`) in commit message.

2021-11-08 17:41 UTC, akiross approved these changes
r+

2021-11-11 09:07 UTC, ronzim commented
Custom tools files were camelCase to be consistent with the original cs tools filename: https://github.com/cornerstonejs/cornerstoneTools/tree/master/src/tools

2021-11-11 09:18 UTC, ronzim commented on imaging/image_tools.js
>  };
Why no callback & no promise here ? 🤔

2021-11-11 21:10 UTC, daron1337 commented
> Custom tools files were camelCase to be consistent with the original cs tools filename: https://github.com/cornerstonejs/cornerstoneTools/tree/master/src/tools

Ouch! @akiross ?

2021-11-11 21:11 UTC, daron1337 commented on imaging/image_tools.js
>  };
It's a sync function

2021-11-15 15:33 UTC, ronzim approved these changes

2021-11-15 15:33 UTC, ronzim commented on MIGRATION.md
> +This guide is primarily for user with prior Larvitar v0.x experience who want to learn about the new features and changes in Larvitar v1.x. While it looks like a lot has changed, a lot of what you kn
Typo "about"

2021-11-16 08:44 UTC, merged