New seg api
dvisionlab/Larvitar pull request #174
Opened 2021-11-16 13:11 UTC by ronzim

2021-11-22 08:47 UTC, daron1337 requested changes
- Change version in package.json and README
- Update compiled larvitar.js in examples

2021-11-22 08:47 UTC, daron1337 commented on imaging/tools/segmentation.js
>  window.cornerstone = cornerstone;
Remove these lines (cornerstone is already exported in index.js btw)

2021-11-24 17:21 UTC, ronzim commented
> * Change version in package.json and README
> * Update compiled larvitar.js in examples

examples are not affected by updates

2021-11-25 08:05 UTC, daron1337 requested changes
- Fix the function call using isElement
- Document the breaking change in the Migration.md file

2021-11-25 08:05 UTC, daron1337 commented on imaging/tools/segmentation.js
> +  }
In order to be consistent with other functions that uses elementId in larvitar, use the isElement function inside

2021-11-26 09:57 UTC, daron1337 commented on imaging/tools/segmentation.js
> +  }
`import { isElement } from "../imageUtils";`

`let element = isElement(elementId)
    ? elementId
    : document.getElementById(elementId);
  if (!element) {
    console.error("invalid html element: " + elementId);
    return;
  }`

2021-11-26 10:15 UTC, daron1337 approved these changes

2021-11-26 10:53 UTC, merged