4dstackscrollwheel
dvisionlab/Larvitar pull request #224
Opened 2023-05-26 13:24 UTC by panizzopoli

Implement a new custom 4D stack tool for mouse wheel

2023-05-26 14:30 UTC, ronzim approved these changes

2023-05-29 08:12 UTC, daron1337 approved these changes

2023-05-29 08:16 UTC, daron1337 requested changes
Una domanda, non era meglio implementarlo già nel branch typescript?

2023-05-29 08:16 UTC, daron1337 commented on imaging/tools/custom/4dSliceScrollTool.js
> +    console.log('Direction ', direction);
toglierei i vari console.log

2023-05-29 08:16 UTC, daron1337 commented on imaging/tools/custom/4dSliceScrollTool.js
> +    console.log('newImageIdIndex calculated ', newImageIdIndex);
toglierei i vari console.log

2023-05-29 08:16 UTC, daron1337 commented on imaging/tools/main.js
> -
cosa è cambiato in questo file tale da generare una diff cosi corposa? linter?

2023-05-29 08:16 UTC, daron1337 commented on imaging/tools/default.js
> - *  @desc  This file provides definitions
cosa è cambiato in questo file tale da generare una diff cosi corposa? linter?

2023-05-29 08:16 UTC, daron1337 commented on docs/examples/4d.html
> -    <meta charset="UTF-8" />
cosa è cambiato in questo file tale da generare una diff cosi corposa? linter?

2023-05-30 08:48 UTC, daron1337 requested changes
- aggiornare versione in README e package.json (incrementiamo la minor)
- vedo ancora troppe diff nel 4d.html, default.js e main.js controlla il lint salvando file, fai una commit e un push per favore

2023-06-01 09:53 UTC, closed without merging