fix: store updates for duplicated viewport props
dvisionlab/Larvitar pull request #238
Opened 2023-08-02 18:49 UTC by zansa

2023-08-03 15:21 UTC, daron1337 approved these changes

2023-08-04 11:07 UTC, ronzim approved these changes

2023-08-04 11:10 UTC, daron1337 requested changes
Sara perfavore fai un rebase dal branch typescript cosi ti prendi le mie modifiche di oggi e poi metti rc15 come release

2023-08-28 08:58 UTC, daron1337 commented
> Sara perfavore fai un rebase dal branch typescript cosi ti prendi le mie modifiche di oggi e poi metti rc15 come release

la versione sarà la 16 o la 17 ora, fai un check

2023-08-30 12:19 UTC, daron1337 approved these changes

2023-08-30 12:22 UTC, merged