Feat meta data types
dvisionlab/Larvitar pull request #259
Opened 2023-10-16 14:38 UTC by akiross

@laura-borghesi-lum00n sistema pure te

2023-10-16 14:39 UTC, daron1337 commented
@akiross è su branch typescript non master la PR

2023-10-16 14:45 UTC, laura-borghesi-lum00n commented
scusate ho fatto casino nel pushing del mio commit. Ho aggiunto la tipizzazione, mancano da sistemare solamente i nested types (quando riesci ti chiedo @daron1337) e domani chiudo

2023-10-16 15:56 UTC, akiross commented
> scusate ho fatto casino nel pushing del mio commit. Ho aggiunto la tipizzazione, mancano da sistemare solamente i nested types (quando riesci ti chiedo @daron1337) e domani chiudo

sì tranquilla, non è nemmeno detto che tu debba usare questa PR e l'ho fatta solo in modo che il commit non fosse perso di vista.

tra l'altro, questa PR è in draft e github non dovrebbe mandare le notifiche, ma c'è un noto bug in github per cui questa cosa succede comunque.

2023-10-19 09:39 UTC, daron1337 requested changes

2023-10-19 09:39 UTC, daron1337 commented on imaging/imageStore.ts
> +  //Laura: shall we use MetaData?
check this

2023-10-19 09:39 UTC, daron1337 commented on imaging/imageUtils.ts
> +      //Laura ?? tagValue = tagValue.map(v => parseFloat(v as string));
check

2023-10-19 09:39 UTC, daron1337 commented on imaging/imageUtils.ts
> +      metadata: metadata //Laura: missing other metadata, problem with MetaDataTypes. Is metadata an array of SOME metadatas?
check

2023-10-19 09:39 UTC, daron1337 commented on imaging/imageUtils.ts
> +  let distanceBetweenSlices = sampleMetadata["x00180050"] //x00180050?? laura
check

2023-10-26 22:33 UTC, daron1337 requested changes
Ho fatto alcuni test in locale e ci sono alcuni problemi con il multiframe e la funzione getSortedStack, dobbiamo guardarci insieme

2023-10-30 15:57 UTC, daron1337 approved these changes

2023-11-01 17:49 UTC, merged