Fix remove wwwcregion
dvisionlab/Larvitar pull request #339
Opened 2024-03-25 14:34 UTC by panizzopoli

Minor fixes on remove ww/wc region tool. Better handling remove. Region rectangle now Black with green border

2024-03-25 15:11 UTC, laura-borghesi-lum00n commented
se rimuovo tutte le Roi draggandole fuori dall'immagine non si resetta il contrasto originale + lascerei gli handles visibili così si capisce dove la Roi è draggabile 
![ORIGINAL](https://github.com/dvisionlab/Larvitar/assets/146220917/7292fdfb-0d04-4fd8-a136-7b417e6ae2b5)
![ROI](https://github.com/dvisionlab/Larvitar/assets/146220917/81d776ab-0394-4479-8c7c-e9b3dae0f064)
![ROIREMOVED](https://github.com/dvisionlab/Larvitar/assets/146220917/d1d27459-0e40-48f1-9db5-caeef2227a87)

2024-03-25 15:13 UTC, laura-borghesi-lum00n requested changes
vedi commento sopra 👍

2024-03-28 09:15 UTC, daron1337 commented
Segnalo due cose:
- se si usa Wwwc, si cambia contrasto ma quando si rilascia il mouse il contrasto torna al suo valore originale. E' voluto?
-  se si seleziona un altro tool (e.g. rotate) i quadrati si spostano se cliccati

2024-03-28 15:44 UTC, laura-borghesi-lum00n commented
- when tool set to passive the Roi is no longer draggable
- when Rois are removed wwwc returns to the original value
- wwwc remove algorithm based on z-test median instead of mean
- aesthetic of handles/contours fixed basing on active/inactive data
- version updated
- name in default tools changed using standards of larvitar
TODO: check if handles must be draggable in order to modify ROI or not

2024-04-03 15:12 UTC, laura-borghesi-lum00n approved these changes

2024-04-05 14:02 UTC, daron1337 requested changes

2024-04-05 14:44 UTC, daron1337 approved these changes

2024-04-05 14:45 UTC, merged